# Generated by Django 4.0 on 2022-05-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('book_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('b_name', models.CharField(blank=True, max_length=100)),
                ('b_desc', models.CharField(blank=True, max_length=150)),
                ('auther', models.CharField(blank=True, max_length=100)),
                ('b_genre', models.CharField(blank=True, max_length=100)),
                ('b_price', models.IntegerField(blank=True)),
                ('b_pic', models.FileField(blank=True, upload_to='books')),
            ],
            options={
                'db_table': 'addbook',
            },
        ),
    ]
