# Generated by Django 4.0 on 2022-05-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_addbook_b_desc'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addbook',
            table='addBook',
        ),
    ]
