# Generated by Django 4.0 on 2022-05-23 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_addbook_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addbook',
            table='addbook',
        ),
    ]
