# Generated by Django 4.0 on 2022-05-24 14:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_addbook_favourite_addbook_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='addbook',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
