# Generated by Django 4.0 on 2022-05-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_addbook_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='addbook',
            managers=[
            ],
        ),
    ]
