# Generated by Django 4.0 on 2022-05-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('register', '0007_alter_addbook_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('c_name', models.CharField(blank=True, max_length=200)),
                ('c_phone', models.IntegerField()),
                ('c_email', models.CharField(blank=True, max_length=100)),
                ('C_msg', models.CharField(blank=True, max_length=300)),
                ('c_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
