# Generated by Django 4.0 on 2022-05-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='c_adrs',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
