# Generated by Django 4.0 on 2022-06-06 12:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_contact_c_adrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='slug',
        ),
        migrations.AddField(
            model_name='addbook',
            name='New_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='b_name', unique=True),
        ),
    ]
