# Generated by Django 4.0.1 on 2022-06-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_remove_addbook_slug_addbook_new_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
