# Generated by Django 4.0.1 on 2022-06-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_rename_c_id_userp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='customer_picture',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
