# Generated by Django 4.0.1 on 2022-06-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_alter_userp_customer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='customer_picture',
            field=models.FileField(blank=True, upload_to='photos/'),
        ),
    ]
