# Generated by Django 4.0 on 2022-06-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_alter_userp_customer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='customer_picture',
            field=models.FileField(blank=True, upload_to='profile'),
        ),
    ]
