# Generated by Django 4.0 on 2022-06-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_customer_alter_shippingaddress_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='purchased_books',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
